server:
  port: 8080
  servlet:
    context-path: /mopic
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles.active: local
  # database
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://database-1.c3bpmkufnh6f.ap-northeast-2.rds.amazonaws.com:3306/mopicdb?characterEncoding=UTF-8
    username: admin
    password: mopic123
    hikari:
      pool-name: hikari-pool
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties:
        rewriteBatchedStatements: true

mybatis:
  type-aliases-package: kr.co.mopic.dto
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

server.servlet.session.timeout: 43200 # 12시간

logging:
 # config: classpath:logback-spring.xml
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    jdbc:
      sqlonly: DEBUG
      resultsettable: DEBUG
      sqltiming: WARN
      audit: WARN
      resultset: WARN
      connection: WARN
    org.springframework.web: DEBUG
    com.zaxxer.hikari.HikariDataSource: ERROR

cloud:
  aws:
    s3:
      bucket: mopic-image-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIARBL7EEIG4HMWPV6I
      secretKey: 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